FROM node:20.18.0

# Definir diretório da aplicação
WORKDIR /app

# Instalar pnpm e wrangler (sem usar corepack!)
RUN npm install -g pnpm@9.1.1 wrangler

# Copiar arquivos de dependência
COPY package.json pnpm-lock.yaml ./

# Desabilitar verificação de integridade (resolve bug da keyid)
ENV PNPM_CONFIG_VERIFY_STORE_INTEGRITY=false

# Instalar dependências
RUN pnpm install

# Copiar o restante da aplicação
COPY . .

# Expor a porta padrão do Vite/Remix
EXPOSE 5173

# Variáveis de ambiente de produção
ENV WRANGLER_SEND_METRICS=false \
    NODE_ENV=production \
    RUNNING_IN_DOCKER=true

# Build da aplicação
RUN pnpm run build

# Comando padrão
CMD ["pnpm", "run", "dockerstart"]
